---
version: '2'
services:
    db:
        build: ./DB
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: passwd
        volumes_from:
            - stats_data

    server:
        build: ./server_node
        ports:
            - 8888:80
        links:
            - db:reto1db
        expose:
            - 80
        volumes_from:
            - stats_data

    tsung:
        build: ./load
        links:
            - server:reto1server
        expose:
            - 80
        ports:
            - 10080:80
        environment:
            RATE: 10
            HITS: 10

    logstash:
        build: ./logstash
        links:
            - elastic:retoelasticsearch
        volumes_from:
            - stats_data

    elastic:
        image: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        expose:
            - 9200
            - 9300
        volumes_from:
            - elasticsearch_data
        command:
            "elasticsearch"

    kibana:
        image: kibana
        links:
            - elastic:elasticsearch
        expose:
            - 5601
        ports:
            - 5601:5601


    # data-only volumes
    elasticsearch_data:
        image: busybox
        volumes:
            - ./data:/usr/share/elasticsearch/data

    stats_data:
        image: busybox
        volumes:
            - ./shared:/shared
